name: 'CI-CD'

on:
    push:
        branches:
            - 'master'

jobs:
    build-test-deploy:
        name: Build, test, and deploy the demo only
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-node@master
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'

            - uses: actions/checkout@master

            - name: 'Install dependency'
              run: npm ci

            - name: 'Build'
              run: npm run build

            - name: 'Test the library'
              run: npm run test:lib

            - name: 'Test the demo app'
              run: npm run test:app

            - name: 'Ship the coverage within the demo website'
              run: cp -r ./coverage ./dist/ngx-image-compress-demo/coverage

            - name: 'Publish to Netlify'
              uses: netlify/actions/cli@master
              with:
                  args: deploy --dir=./dist/ngx-image-compress-demo --message "${{ github.event.head_commit.message }}" --prod --open
              env:
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
