name: "CI on pull request"

on:
  pull_request:
    branches:
      - "master"

jobs:
  test-pr:
    name: "Build and test for every new PR submitted"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@master
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/checkout@master

      - name: "Install dependency"
        run: npm ci

      - name: 'Build the library'
        run: npm run build:lib

      - name: 'Build the demo app'
        run: npm run build:app

      - name: 'Test the library'
        run: npm run test:lib

      - name: 'Test the demo app'
        run: npm run test:app